### ISSUE TITLE
Error: IDE0006

### ISSUE THREAD

**Issue by EmanDev** [derdanielb/Dota-2-Chat-Wheel-Soundboard#3]
![1](https://user-images.githubusercontent.com/25047362/42122831-5e700474-7c7a-11e8-8eff-8eb45c81fbee.png)
I was planning to add newest TI8 chat-wheels, and then this error occur.
I'm still new to c# btw.

**Comment by EmanDev** [comment]
Fixed by restoring & updating the nugget packages.

**Comment by derdanielb** [comment]
Glad you could solve it on your own.
